### ISSUE TITLE
Update the setup guide

### ISSUE THREAD

**Issue by Nathanael-R** [NativeNotify/nn-expo-push-notifications#1]
The setup guide needs to be updated to reflect the current stages of installation of the package. For example
` npm i nn-expo-push-notifications` 
no longer works

![image](https://github.com/NativeNotify/nn-expo-push-notifications/assets/72811283/9432026b-bb75-4aaf-a764-24d2df774737)

**Comment by pagecow** [comment]
Hi Nathanael. Thanks for pointing this out! 

We created a new Expo push notification npm package name "native-notify". 

nn-expo-push-notifications is no longer being updated.
